# Generated by Django 5.2.7 on 2026-03-25 05:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payment_method',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('upi', 'UPI'), ('bank', 'Bank Transfer'), ('card', 'Card'), ('cheque', 'Cheque')], default='cash', max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reference_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
