# Generated by Django 5.2.7 on 2026-04-03 07:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('report_type', models.CharField(choices=[('performance', 'Performance'), ('financial', 'Financial'), ('attendance', 'Attendance'), ('team', 'Team'), ('player', 'Player'), ('medical', 'Medical'), ('other', 'Other')], default='other', max_length=30)),
                ('category', models.CharField(blank=True, max_length=120)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('summary', models.TextField(blank=True)),
                ('description', models.TextField(blank=True)),
                ('prepared_by', models.CharField(blank=True, max_length=150)),
                ('report_date', models.DateField(default=django.utils.timezone.now)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-report_date', '-created_at'],
            },
        ),
    ]
