# Generated by Django 5.2.7 on 2026-03-31 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournaments', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CompetitionAlert',
        ),
        migrations.AlterUniqueTogether(
            name='tournamentteam',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='tournamentteam',
            name='team',
        ),
        migrations.RemoveField(
            model_name='tournamentteam',
            name='tournament',
        ),
        migrations.AlterModelOptions(
            name='tournament',
            options={'ordering': ['-id']},
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='sport_category',
        ),
        migrations.RemoveField(
            model_name='tournament',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='tournament',
            name='contact_person',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tournament',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='tournament',
            name='gender_category',
            field=models.CharField(blank=True, default='Mixed', max_length=50),
        ),
        migrations.AddField(
            model_name='tournament',
            name='matches_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tournament',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='organizer',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='tournament',
            name='registration_last_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='rules',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='tournament',
            name='sport',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tournament',
            name='teams_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='age_group',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='format',
            field=models.CharField(choices=[('LEAGUE', 'League'), ('KNOCKOUT', 'Knockout'), ('ROUND_ROBIN', 'Round Robin'), ('GROUP_STAGE', 'Group Stage')], default='LEAGUE', max_length=50),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='max_teams',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='tournament',
            name='status',
            field=models.CharField(choices=[('Draft', 'Draft'), ('Open', 'Open'), ('Scheduled', 'Scheduled'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled')], default='Draft', max_length=50),
        ),
        migrations.DeleteModel(
            name='TournamentMatch',
        ),
        migrations.DeleteModel(
            name='TournamentTeam',
        ),
    ]
