# Generated by Django 5.2.7 on 2026-04-06 11:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('match_officials', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='official',
            options={'ordering': ['-id'], 'verbose_name': 'Official', 'verbose_name_plural': 'Officials'},
        ),
        migrations.AlterField(
            model_name='official',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='official',
            name='city',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='official',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='official',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='official',
            name='official_code',
            field=models.CharField(blank=True, max_length=30, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='official',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='official',
            name='qualification',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='official',
            name='sport',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
