# Generated by Django 5.2.7 on 2026-03-28 07:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('match_officials', '0001_initial'),
        ('teams', '0003_alter_team_academic_year_alter_team_achievements_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('round_type', models.CharField(choices=[('league', 'League'), ('quarter_final', 'Quarter Final'), ('semi_final', 'Semi Final'), ('final', 'Final'), ('friendly', 'Friendly')], default='league', max_length=30)),
                ('match_date', models.DateField()),
                ('match_time', models.TimeField()),
                ('venue', models.CharField(max_length=255)),
                ('team_a_score', models.PositiveIntegerField(default=0)),
                ('team_b_score', models.PositiveIntegerField(default=0)),
                ('status', models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed'), ('rescheduled', 'Rescheduled')], default='scheduled', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('reschedule_reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('alternate_official', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='alternate_official_match_module_matches', to='match_officials.official')),
                ('main_official', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='main_official_match_module_matches', to='match_officials.official')),
                ('team_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_module_team_a_matches', to='teams.team')),
                ('team_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_module_team_b_matches', to='teams.team')),
            ],
            options={
                'ordering': ['-match_date', '-match_time', '-id'],
            },
        ),
    ]
