# Generated by Django 5.2.7 on 2026-03-31 07:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0002_initial'),
        ('teams', '0004_alter_team_options_remove_team_created_at_and_more'),
        ('tournaments', '0002_delete_competitionalert_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-match_date', '-id']},
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team_a_score',
            new_name='team1_score',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team_b_score',
            new_name='team2_score',
        ),
        migrations.RemoveField(
            model_name='match',
            name='alternate_official',
        ),
        migrations.RemoveField(
            model_name='match',
            name='main_official',
        ),
        migrations.RemoveField(
            model_name='match',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='match',
            name='reschedule_reason',
        ),
        migrations.RemoveField(
            model_name='match',
            name='round_type',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_a',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team_b',
        ),
        migrations.RemoveField(
            model_name='match',
            name='winner',
        ),
        migrations.AddField(
            model_name='match',
            name='match_title',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='match',
            name='remarks',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='match',
            name='result',
            field=models.CharField(choices=[('team1', 'Team 1 Won'), ('team2', 'Team 2 Won'), ('draw', 'Draw'), ('pending', 'Pending')], default='pending', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='sport_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='stage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='match',
            name='team1',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='teams.team'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='team2',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='teams.team'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='match',
            name='match_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('ongoing', 'Ongoing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('postponed', 'Postponed')], default='scheduled', max_length=20),
        ),
        migrations.AlterField(
            model_name='match',
            name='tournament',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='matches', to='tournaments.tournament'),
        ),
        migrations.AlterField(
            model_name='match',
            name='venue',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
