# Generated by Django 5.2.7 on 2026-03-31 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matches', '0003_alter_match_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='match',
            options={'ordering': ['-match_date', '-created_at']},
        ),
        migrations.RenameField(
            model_name='match',
            old_name='remarks',
            new_name='notes',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team1_score',
            new_name='score_team_a',
        ),
        migrations.RenameField(
            model_name='match',
            old_name='team2_score',
            new_name='score_team_b',
        ),
        migrations.RemoveField(
            model_name='match',
            name='match_title',
        ),
        migrations.RemoveField(
            model_name='match',
            name='result',
        ),
        migrations.RemoveField(
            model_name='match',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team1',
        ),
        migrations.RemoveField(
            model_name='match',
            name='team2',
        ),
        migrations.RemoveField(
            model_name='match',
            name='tournament',
        ),
        migrations.AddField(
            model_name='match',
            name='match_type',
            field=models.CharField(choices=[('league', 'League'), ('knockout', 'Knockout'), ('friendly', 'Friendly'), ('practice', 'Practice')], default='league', max_length=20),
        ),
        migrations.AddField(
            model_name='match',
            name='referee_name',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='match',
            name='round_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='match',
            name='team_a',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='team_b',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='title',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='tournament_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='match',
            name='winner',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AlterField(
            model_name='match',
            name='sport_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='match',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Scheduled'), ('live', 'Live'), ('completed', 'Completed'), ('postponed', 'Postponed'), ('cancelled', 'Cancelled')], default='scheduled', max_length=20),
        ),
    ]
