# Generated by Django 5.2.7 on 2026-04-04 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_alter_inventoryitem_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorycategory',
            options={'ordering': ['name'], 'verbose_name': 'Inventory Category', 'verbose_name_plural': 'Inventory Categories'},
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['-id'], 'verbose_name': 'Inventory Item', 'verbose_name_plural': 'Inventory Items'},
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='inventorycategory',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('low_stock', 'Low Stock'), ('out_of_stock', 'Out Of Stock')], default='available', max_length=30),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
