# Generated by Django 5.2.7 on 2026-04-06 04:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_inventorycategory_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inventorycategory',
            options={'ordering': ['name'], 'verbose_name_plural': 'Inventory Categories'},
        ),
        migrations.AlterModelOptions(
            name='inventoryitem',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='inventoryitem',
            old_name='name',
            new_name='item_name',
        ),
        migrations.RemoveField(
            model_name='inventorycategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='inventorycategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='inventorycategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='inventoryitem',
            name='purchase_date',
        ),
        migrations.AddField(
            model_name='inventoryitem',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='inventorycategory',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='brand',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='items', to='inventory.inventorycategory'),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='location',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='sku',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='supplier',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='inventoryitem',
            name='unit_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
