# Generated by Django 5.2.7 on 2026-03-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PerformanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('admission_no', models.CharField(blank=True, max_length=100, null=True)),
                ('class_name', models.CharField(blank=True, max_length=100, null=True)),
                ('section', models.CharField(blank=True, max_length=50, null=True)),
                ('sport', models.CharField(choices=[('Cricket', 'Cricket'), ('Football', 'Football'), ('Kabaddi', 'Kabaddi'), ('Volleyball', 'Volleyball'), ('Athletics', 'Athletics'), ('Chess', 'Chess'), ('Badminton', 'Badminton'), ('Other', 'Other')], default='Other', max_length=100)),
                ('event_name', models.CharField(max_length=255)),
                ('performance_date', models.DateField()),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('grade', models.CharField(blank=True, max_length=50, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('improvement_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-performance_date', '-id'],
            },
        ),
    ]
