# Generated by Django 5.2.7 on 2026-04-04 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('performance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(max_length=255)),
                ('sport', models.CharField(max_length=100)),
                ('event_name', models.CharField(blank=True, default='', max_length=150)),
                ('performance_score', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('performance_level', models.CharField(choices=[('excellent', 'Excellent'), ('good', 'Good'), ('average', 'Average'), ('needs_improvement', 'Needs Improvement')], default='average', max_length=30)),
                ('performance_date', models.DateField(blank=True, null=True)),
                ('coach_name', models.CharField(blank=True, default='', max_length=255)),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-performance_date', '-id'],
            },
        ),
        migrations.DeleteModel(
            name='PerformanceRecord',
        ),
    ]
