# Generated by Django 5.2.7 on 2026-03-30 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GrantRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_name', models.CharField(max_length=255)),
                ('sponsor_name', models.CharField(blank=True, max_length=255, null=True)),
                ('scheme_type', models.CharField(blank=True, max_length=100, null=True)),
                ('applied_date', models.DateField()),
                ('amount_requested', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_approved', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('Applied', 'Applied'), ('Under Review', 'Under Review'), ('Approved', 'Approved'), ('Rejected', 'Rejected'), ('Received', 'Received')], default='Applied', max_length=50)),
                ('contact_person', models.CharField(blank=True, max_length=255, null=True)),
                ('mobile_number', models.CharField(blank=True, max_length=20, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-applied_date', '-id'],
            },
        ),
    ]
