# Generated by Django 5.2.7 on 2026-04-04 04:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('grants', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Grant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grant_name', models.CharField(max_length=255)),
                ('grant_type', models.CharField(choices=[('sports', 'Sports'), ('education', 'Education'), ('medical', 'Medical'), ('infrastructure', 'Infrastructure'), ('equipment', 'Equipment'), ('training', 'Training'), ('other', 'Other')], default='sports', max_length=50)),
                ('funding_agency', models.CharField(blank=True, default='', max_length=255)),
                ('amount_requested', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount_approved', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('draft', 'Draft')], default='pending', max_length=20)),
                ('applied_date', models.DateField(blank=True, null=True)),
                ('approval_date', models.DateField(blank=True, null=True)),
                ('purpose', models.TextField(blank=True, default='')),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-applied_date', '-id'],
            },
        ),
        migrations.DeleteModel(
            name='GrantRecord',
        ),
    ]
