# Generated by Django 5.2.7 on 2026-04-06 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mediaitem',
            options={'ordering': ['-id']},
        ),
        migrations.RenameField(
            model_name='mediaitem',
            old_name='is_featured',
            new_name='is_published',
        ),
        migrations.RemoveField(
            model_name='mediacategory',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='mediacategory',
            name='description',
        ),
        migrations.RemoveField(
            model_name='mediacategory',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='mediaitem',
            name='caption',
        ),
        migrations.RemoveField(
            model_name='mediaitem',
            name='file_size',
        ),
        migrations.RemoveField(
            model_name='mediaitem',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='mediaitem',
            name='uploaded_by',
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='mediaitem',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('team', 'Team')], default='public', max_length=30),
        ),
        migrations.AlterField(
            model_name='mediacategory',
            name='name',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='event_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='media_items/'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='media_type',
            field=models.CharField(choices=[('image', 'Image'), ('video', 'Video'), ('document', 'Document'), ('audio', 'Audio')], default='image', max_length=30),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='sport_name',
            field=models.CharField(blank=True, default='', max_length=150),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='active', max_length=30),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='media_thumbnails/'),
        ),
        migrations.AlterField(
            model_name='mediaitem',
            name='title',
            field=models.CharField(max_length=220),
        ),
    ]
