# Generated by Django 5.2.7 on 2026-03-24 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('team_name', models.CharField(max_length=150, unique=True)),
                ('sport', models.CharField(max_length=100)),
                ('age_group', models.CharField(blank=True, max_length=50)),
                ('gender_category', models.CharField(choices=[('boys', 'Boys'), ('girls', 'Girls'), ('mixed', 'Mixed')], default='boys', max_length=20)),
                ('coach_name', models.CharField(blank=True, max_length=150)),
                ('captain_name', models.CharField(blank=True, max_length=150)),
                ('vice_captain_name', models.CharField(blank=True, max_length=150)),
                ('player_count', models.PositiveIntegerField(default=0)),
                ('academic_year', models.CharField(blank=True, max_length=20)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('archived', 'Archived')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['-created_at'],
            },
        ),
    ]
