# Generated by Django 5.2.7 on 2026-03-25 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='team',
            options={'ordering': ['team_name']},
        ),
        migrations.RenameField(
            model_name='team',
            old_name='player_count',
            new_name='current_players_count',
        ),
        migrations.RenameField(
            model_name='team',
            old_name='sport',
            new_name='sport_name',
        ),
        migrations.RemoveField(
            model_name='team',
            name='description',
        ),
        migrations.AddField(
            model_name='team',
            name='achievements',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='team',
            name='max_players',
            field=models.PositiveIntegerField(default=11),
        ),
        migrations.AddField(
            model_name='team',
            name='notes',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='team',
            name='academic_year',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='age_group',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='captain_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='team',
            name='coach_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterField(
            model_name='team',
            name='gender_category',
            field=models.CharField(choices=[('Boys', 'Boys'), ('Girls', 'Girls'), ('Mixed', 'Mixed')], default='Mixed', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='status',
            field=models.CharField(choices=[('Active', 'Active'), ('Inactive', 'Inactive'), ('Archived', 'Archived')], default='Active', max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='vice_captain_name',
            field=models.CharField(blank=True, default='', max_length=120),
        ),
        migrations.AlterModelTable(
            name='team',
            table='teams',
        ),
    ]
