# Generated by Django 5.2.7 on 2026-03-27 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0002_alter_team_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='academic_year',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='team',
            name='achievements',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='age_group',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='team',
            name='captain_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='team',
            name='coach_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterField(
            model_name='team',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='team',
            name='sport_name',
            field=models.CharField(max_length=120),
        ),
        migrations.AlterField(
            model_name='team',
            name='vice_captain_name',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AlterModelTable(
            name='team',
            table=None,
        ),
    ]
